services:
  omejdn:
    image: nginx:1.25.3
    container_name: omejdn
    ports:
      - 80:80
      - 443:443      
    environment:
      - OMEJDN_DOMAIN=${OMEJDN_DOMAIN}
      - OMEJDN_PATH=${OMEJDN_PATH}
      - UI_PATH=${UI_PATH}
    volumes:
      - ./DAPS/nginx.conf:/etc/nginx/templates/default.conf.template
      - ./DAPS/keys/TLS/daps.cert:/etc/nginx/daps.cert
      - ./DAPS/keys/TLS/daps.key:/etc/nginx/daps.key
    networks:
      - local

  omejdn-server:
    image: ghcr.io/fraunhofer-aisec/omejdn-server:${OMEJDN_VERSION}
    container_name: omejdn-server
    environment:
      - OMEJDN_ISSUER=${OMEJDN_ISSUER}
      - OMEJDN_FRONT_URL=${OMEJDN_ISSUER}
      - OMEJDN_OPENID=true
      - OMEJDN_ENVIRONMENT=${OMEJDN_ENVIRONMENT}
      - OMEJDN_ACCEPT_AUDIENCE=idsc:IDS_CONNECTORS_ALL
      - OMEJDN_DEFAULT_AUDIENCE=idsc:IDS_CONNECTORS_ALL
      - OMEJDN_ADMIN=${ADMIN_USERNAME}:${ADMIN_PASSWORD}
    volumes:
      - ./DAPS/config:/opt/config
      - ./DAPS/keys:/opt/keys
    networks:
      - local

  omejdn-ui:
    image: ghcr.io/fraunhofer-aisec/omejdn-ui:${UI_VERSION}
    container_name: omejdn-ui
    environment:
      - OIDC_ISSUER=${OMEJDN_ISSUER}
      - API_URL=${OMEJDN_ISSUER}/api/v1
      - CLIENT_ID=adminUI
    networks:
      - local

# Add the PostgreSQL container to be used by DataspaceConnectorA and DataspaceConnectorB
  postgresa:
    image: postgres:13
    container_name: 'postgresa-container'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgresusera
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=connectoradb
    volumes:
      - connector-dataa:/var/lib/postgresql/data
    networks:
      - local
      
  postgresb:
    image: postgres:13
    container_name: 'postgresb-container'
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgresuserb
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=connectorbdb
    volumes:
      - connector-datab:/var/lib/postgresql/data
    networks:
      - local

  postgresmhtroo:
    image: postgres:13
    container_name: 'postgresmhtroo-container'
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgresusermhtroo
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=connectormhtroodb
    volumes:
      - connector-datamhtroo:/var/lib/postgresql/data
    networks:
      - local
  
  postgresameaclub:
    image: postgres:13
    container_name: 'postgresameaclub-container'
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgresuserameaclub
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=connectorameaclubdb
    volumes:
      - connector-dataameaclub:/var/lib/postgresql/data
    networks:
      - local
  
  postgresnaturaldisaster:
    image: postgres:13
    container_name: 'postgresnaturaldisaster-container'
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_USER=postgresusernaturaldisaster
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=connectornaturaldisasterdb
    volumes:
      - connector-datanaturaldisaster:/var/lib/postgresql/data
    networks:
      - local

  postgrescivilservice:
    image: postgres:13
    container_name: 'postgrescivilservice-container'
    ports:
      - "5437:5432"
    environment:
      - POSTGRES_USER=postgresusercivilservice
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=connectorcivilservicedb
    volumes:
      - connector-datacivilservice:/var/lib/postgresql/data
    networks:
      - local


  connectora:
    image: ghcr.io/international-data-spaces-association/dataspace-connector:8.0.2
    container_name: connectora
    ports:
      - 8080:8080
    environment:
      - SPRING_AUTOCONFIGURE_EXCLUDE=org.springframework.boot.actuate.autoconfigure.metrics.SystemMetricsAutoConfiguration
      - CONFIGURATION_PATH=/config/config.json
      - DAPS_URL=https://omejdn
      - DAPS_TOKEN_URL=https://omejdn/auth/token
      - DAPS_KEY_URL=https://omejdn/auth/jwks.json
      - DAPS_INCOMING_DAT_DEFAULT_WELLKNOWN=/jwks.json
      - SERVER_SSL_KEY-STORE=file:///conf/connectorA.p12
      # Define the PostgreSQL setup
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresa:5432/connectoradb 
      - SPRING_DATASOURCE_PLATFORM=postgres
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - SPRING_DATASOURCE_USERNAME=postgresusera
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      # Timeouts for HTTP requests
      - HTTP_TIMEOUT_CONNECT=20000
      - HTTP_TIMEOUT_READ=20000
      - HTTP_TIMEOUT_WRITE=20000
      - HTTP_TIMEOUT_CALL=20000
    volumes:
      - ./DataspaceConnectorA/conf/config.json:/config/config.json
      - ./DataspaceConnectorA/conf/connectorA.p12:/conf/connectorA.p12
      - ./DataspaceConnectorA/conf/truststore.p12:/config/truststore.p12
    networks:
      - local
    depends_on:
      - postgresa
      
  connectorb:
    image: ghcr.io/international-data-spaces-association/dataspace-connector:8.0.2
    container_name: connectorb
    ports:
      - 8081:8081
    environment:
      - SPRING_AUTOCONFIGURE_EXCLUDE=org.springframework.boot.actuate.autoconfigure.metrics.SystemMetricsAutoConfiguration
      - CONFIGURATION_PATH=/config/config.json
      - SERVER_PORT=8081
      - DAPS_URL=https://omejdn
      - DAPS_TOKEN_URL=https://omejdn/auth/token
      - DAPS_KEY_URL=https://omejdn/auth/jwks.json
      - DAPS_INCOMING_DAT_DEFAULT_WELLKNOWN=/jwks.json
      - SERVER_SSL_KEY-STORE=file:///conf/connectorB.p12
      # Define the PostgreSQL setup     
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresb:5432/connectorbdb 
      - SPRING_DATASOURCE_USERNAME=postgresuserb
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_PLATFORM=postgres
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      # Timeouts for HTTP requests
      - HTTP_TIMEOUT_CONNECT=20000
      - HTTP_TIMEOUT_READ=20000
      - HTTP_TIMEOUT_WRITE=20000
      - HTTP_TIMEOUT_CALL=20000
    volumes:
      - ./DataspaceConnectorB/conf/config.json:/config/config.json
      - ./DataspaceConnectorB/conf/connectorB.p12:/conf/connectorB.p12
      - ./DataspaceConnectorB/conf/truststore.p12:/config/truststore.p12
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - local


    depends_on:
      - postgresb

  connectormhtroo:
    image: ghcr.io/international-data-spaces-association/dataspace-connector:8.0.2
    container_name: connectormhtroo
    ports:
      - 8082:8082
    environment:
      - SPRING_AUTOCONFIGURE_EXCLUDE=org.springframework.boot.actuate.autoconfigure.metrics.SystemMetricsAutoConfiguration
      - SERVER_PORT=8082
      - CONFIGURATION_PATH=/config/config.json
      - DAPS_URL=https://omejdn
      - DAPS_TOKEN_URL=https://omejdn/auth/token
      - DAPS_KEY_URL=https://omejdn/auth/jwks.json
      - DAPS_INCOMING_DAT_DEFAULT_WELLKNOWN=/jwks.json
      - SERVER_SSL_KEY-STORE=file:///conf/connectorMhtroo.p12
      # Define the PostgreSQL setup
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresmhtroo:5432/connectormhtroodb 
      - SPRING_DATASOURCE_PLATFORM=postgres
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - SPRING_DATASOURCE_USERNAME=postgresusermhtroo
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      # Timeouts for HTTP requests
      - HTTP_TIMEOUT_CONNECT=20000
      - HTTP_TIMEOUT_READ=20000
      - HTTP_TIMEOUT_WRITE=20000
      - HTTP_TIMEOUT_CALL=20000
    volumes:
      - ./DataspaceConnectorMhtroo/conf/config.json:/config/config.json
      - ./DataspaceConnectorMhtroo/conf/connectorMhtroo.p12:/conf/connectorMhtroo.p12
      - ./DataspaceConnectorMhtroo/conf/truststore.p12:/config/truststore.p12
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      local:
        aliases:
          - connectormhtroo
    depends_on:
      - postgresmhtroo
    

  connectorameaclub:
    image: ghcr.io/international-data-spaces-association/dataspace-connector:8.0.2
    container_name: connectorameaclub
    ports:
      - 8083:8083
    environment:
      - SPRING_AUTOCONFIGURE_EXCLUDE=org.springframework.boot.actuate.autoconfigure.metrics.SystemMetricsAutoConfiguration
      - SERVER_PORT=8083
      - CONFIGURATION_PATH=/config/config.json

      # DAPS (same as your other connectors)
      - DAPS_URL=https://omejdn
      - DAPS_TOKEN_URL=https://omejdn/auth/token
      - DAPS_KEY_URL=https://omejdn/auth/jwks.json
      - DAPS_INCOMING_DAT_DEFAULT_WELLKNOWN=/jwks.json

      # TLS/keystore
      - SERVER_SSL_KEY-STORE=file:///conf/connectorAmeaclub.p12

      # Postgres (points to the new DB)
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresameaclub:5432/connectorameaclubdb
      - SPRING_DATASOURCE_PLATFORM=postgres
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - SPRING_DATASOURCE_USERNAME=postgresuserameaclub
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect

      # Timeouts
      - HTTP_TIMEOUT_CONNECT=20000
      - HTTP_TIMEOUT_READ=20000
      - HTTP_TIMEOUT_WRITE=20000
      - HTTP_TIMEOUT_CALL=20000

    volumes:
      - ./DataspaceConnectorAmeaclub/conf/config.json:/config/config.json
      - ./DataspaceConnectorAmeaclub/conf/connectorAmeaclub.p12:/conf/connectorAmeaclub.p12
      - ./DataspaceConnectorAmeaclub/conf/truststore.p12:/config/truststore.p12

    extra_hosts:
      - "host.docker.internal:host-gateway"

    networks:
      local:
        aliases:
          - connectorameaclub

    depends_on:
      - postgresameaclub

  connectornaturaldisaster:
    image: ghcr.io/international-data-spaces-association/dataspace-connector:8.0.2
    container_name: connectornaturaldisaster
    ports:
      - 8084:8084
    environment:
      - SPRING_AUTOCONFIGURE_EXCLUDE=org.springframework.boot.actuate.autoconfigure.metrics.SystemMetricsAutoConfiguration
      - SERVER_PORT=8084
      - CONFIGURATION_PATH=/config/config.json
      # DAPS
      - DAPS_URL=https://omejdn
      - DAPS_TOKEN_URL=https://omejdn/auth/token
      - DAPS_KEY_URL=https://omejdn/auth/jwks.json
      - DAPS_INCOMING_DAT_DEFAULT_WELLKNOWN=/jwks.json
      # TLS/keystore
      - SERVER_SSL_KEY-STORE=file:///conf/connectorNaturaldisaster.p12
      # Postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresnaturaldisaster:5432/connectornaturaldisasterdb
      - SPRING_DATASOURCE_PLATFORM=postgres
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - SPRING_DATASOURCE_USERNAME=postgresusernaturaldisaster
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      # Timeouts
      - HTTP_TIMEOUT_CONNECT=20000
      - HTTP_TIMEOUT_READ=20000
      - HTTP_TIMEOUT_WRITE=20000
      - HTTP_TIMEOUT_CALL=20000
    volumes:
      - ./DataspaceConnectorNaturaldisaster/conf/config.json:/config/config.json
      - ./DataspaceConnectorNaturaldisaster/conf/connectorNaturaldisaster.p12:/conf/connectorNaturaldisaster.p12
      - ./DataspaceConnectorNaturaldisaster/conf/truststore.p12:/config/truststore.p12
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      local:
        aliases:
          - connectornaturaldisaster
    depends_on:
      - postgresnaturaldisaster

  connectorcivilservice:
    image: ghcr.io/international-data-spaces-association/dataspace-connector:8.0.2
    container_name: connectorcivilservice
    ports:
      - 8085:8085
    environment:
      - SPRING_AUTOCONFIGURE_EXCLUDE=org.springframework.boot.actuate.autoconfigure.metrics.SystemMetricsAutoConfiguration
      - SERVER_PORT=8085
      - CONFIGURATION_PATH=/config/config.json

      # DAPS (same as your other connectors)
      - DAPS_URL=https://omejdn
      - DAPS_TOKEN_URL=https://omejdn/auth/token
      - DAPS_KEY_URL=https://omejdn/auth/jwks.json
      - DAPS_INCOMING_DAT_DEFAULT_WELLKNOWN=/jwks.json

      # TLS/keystore (note capital C in file name)
      - SERVER_SSL_KEY-STORE=file:///conf/connectorCivilservice.p12

      # Postgres for Civilservice
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgrescivilservice:5432/connectorcivilservicedb
      - SPRING_DATASOURCE_PLATFORM=postgres
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - SPRING_DATASOURCE_USERNAME=postgresusercivilservice
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect

      # Timeouts
      - HTTP_TIMEOUT_CONNECT=20000
      - HTTP_TIMEOUT_READ=20000
      - HTTP_TIMEOUT_WRITE=20000
      - HTTP_TIMEOUT_CALL=20000

    volumes:
      - ./DataspaceConnectorCivilservice/conf/config.json:/config/config.json
      - ./DataspaceConnectorCivilservice/conf/connectorCivilservice.p12:/conf/connectorCivilservice.p12
      - ./DataspaceConnectorCivilservice/conf/truststore.p12:/config/truststore.p12

    extra_hosts:
      - "host.docker.internal:host-gateway"

    networks:
      local:
        aliases:
          - connectorcivilservice

    depends_on:
      - postgrescivilservice

  broker-reverseproxy:
    image: idstestbed/mdb-reverseproxy:5.0.3
    container_name: broker-reverseproxy
    volumes:
      - ./MetadataBroker/server.crt:/etc/cert/server.crt
      - ./MetadataBroker/server.key:/etc/cert/server.key
    ports:
      - "444:443" # IDS-HTTP API
      - "81:80"
    networks:
      - local

  broker-core:
    image: idstestbed/metadatabroker-core:5.0.3
    container_name: broker-core
    volumes:
      - ./MetadataBroker/isstbroker-keystore.jks:/etc/cert/isstbroker-keystore.jks
    environment:
      - SPARQL_ENDPOINT=http://broker-fuseki:3030/connectorData
      - ELASTICSEARCH_HOSTNAME=broker-elasticsearch
      - SHACL_VALIDATION=true
      - DAPS_VALIDATE_INCOMING=true
      - COMPONENT_URI=https://broker-reverseproxy/
      - COMPONENT_CATALOGURI=https://broker-reverseproxy/connectors/
      - DAPS_URL=https://omejdn/auth/token
    expose:
      - "8080"
    networks:
      - local

  broker-fuseki:
    image: idstestbed/mdb-fuseki:5.0.3
    container_name: broker-fuseki
    volumes:
      - broker-fuseki:/fuseki
    expose:
      - "3030"
    networks:
      - local

volumes:
  broker-fuseki: {}
  connector-dataa: {}
  connector-datab: {}
  connector-datamhtroo: {}
  connector-dataameaclub: {}
  connector-datanaturaldisaster: {}
  connector-datacivilservice: {}



networks:
  local:
    driver: bridge