---
- client_id: EB:D2:46:C7:7A:B8:DC:48:9D:AB:1D:31:2A:08:41:48:D7:5F:12:55:keyid:C4:76:D0:AA:CD:93:79:35:0F:EB:A7:64:60:90:A4:6B:B4:38:4D:33
  client_name: broker
  grant_types: client_credentials
  token_endpoint_auth_method: private_key_jwt
  scope: idsc:IDS_CONNECTOR_ATTRIBUTES_ALL
  attributes:
  - key: idsc
    value: IDS_CONNECTOR_ATTRIBUTES_ALL
  - key: securityProfile
    value: idsc:BASE_SECURITY_PROFILE
  - key: referringConnector
    value: http://broker.demo
  - key: "@type"
    value: ids:DatPayload
  - key: "@context"
    value: https://w3id.org/idsa/contexts/context.jsonld
  - key: transportCertsSha256
    value: edd4bf74e9850f8a55b82f410db228e1a46d884ea533d721e18405e2769edcb9
- client_id: 05:7E:2E:7C:71:33:28:0D:18:0E:BB:40:7D:A7:6C:1C:64:37:8A:62:keyid:C4:76:D0:AA:CD:93:79:35:0F:EB:A7:64:60:90:A4:6B:B4:38:4D:33
  client_name: connectorA
  grant_types: client_credentials
  token_endpoint_auth_method: private_key_jwt
  scope: idsc:IDS_CONNECTOR_ATTRIBUTES_ALL
  attributes:
  - key: idsc
    value: IDS_CONNECTOR_ATTRIBUTES_ALL
  - key: securityProfile
    value: idsc:BASE_SECURITY_PROFILE
  - key: referringConnector
    value: http://connectorA.demo
  - key: "@type"
    value: ids:DatPayload
  - key: "@context"
    value: https://w3id.org/idsa/contexts/context.jsonld
  - key: transportCertsSha256
    value: 45599b692a3892cd6c492bc95fae95b194c496155ee9d237153e15cd43d19016
- client_id: E7:23:AA:9F:21:18:6A:0F:CB:99:37:A3:5D:B8:DF:65:F0:5B:31:FE:keyid:C4:76:D0:AA:CD:93:79:35:0F:EB:A7:64:60:90:A4:6B:B4:38:4D:33
  client_name: connectorB
  grant_types: client_credentials
  token_endpoint_auth_method: private_key_jwt
  scope: idsc:IDS_CONNECTOR_ATTRIBUTES_ALL
  attributes:
  - key: idsc
    value: IDS_CONNECTOR_ATTRIBUTES_ALL
  - key: securityProfile
    value: idsc:BASE_SECURITY_PROFILE
  - key: referringConnector
    value: http://connectorB.demo
  - key: "@type"
    value: ids:DatPayload
  - key: "@context"
    value: https://w3id.org/idsa/contexts/context.jsonld
  - key: transportCertsSha256
    value: 31741d12bd09dff4d0beb31b6d42811788e4d8954910a985d70d3127630a188d
- client_id: 6B:97:E6:16:AD:4D:F8:15:62:D1:0D:A1:70:CC:FF:66:45:0B:A6:6C:keyid:C4:76:D0:AA:CD:93:79:35:0F:EB:A7:64:60:90:A4:6B:B4:38:4D:33
  client_name: connectorMhtroo
  grant_types: client_credentials
  token_endpoint_auth_method: private_key_jwt
  scope: idsc:IDS_CONNECTOR_ATTRIBUTES_ALL
  attributes:
  - key: idsc
    value: IDS_CONNECTOR_ATTRIBUTES_ALL
  - key: securityProfile
    value: idsc:BASE_SECURITY_PROFILE
  - key: referringConnector
    value: http://connectorMhtroo.demo
  - key: "@type"
    value: ids:DatPayload
  - key: "@context"
    value: https://w3id.org/idsa/contexts/context.jsonld
  - key: transportCertsSha256
    value: 376a206892492b4ea4632f5570d2e885956ebd676b273afa8698e9a67977dd51
- client_id: F3:53:5B:30:7C:3C:9B:98:68:83:10:18:E1:15:E5:EC:03:29:00:76:keyid:C4:76:D0:AA:CD:93:79:35:0F:EB:A7:64:60:90:A4:6B:B4:38:4D:33
  client_name: connectorAmeaclub
  grant_types: client_credentials
  token_endpoint_auth_method: private_key_jwt
  scope: idsc:IDS_CONNECTOR_ATTRIBUTES_ALL
  attributes:
  - key: idsc
    value: IDS_CONNECTOR_ATTRIBUTES_ALL
  - key: securityProfile
    value: idsc:BASE_SECURITY_PROFILE
  - key: referringConnector
    value: http://connectorAmeaclub.demo
  - key: "@type"
    value: ids:DatPayload
  - key: "@context"
    value: https://w3id.org/idsa/contexts/context.jsonld
  - key: transportCertsSha256
    value: c1b50bf0abb2b2183e79e7c602c0319e6d4d24753e844548e5af3467ac118376
- client_id: 10:17:03:AC:A5:41:8D:D1:3F:FD:4F:EE:85:D9:EB:CC:5B:4A:70:F8:keyid:19:A0:3E:93:17:75:B1:DE:BF:3F:B2:29:F2:FB:02:59:3E:CA:6E:2D
  client_name: connectorNaturaldisaster
  grant_types: client_credentials
  token_endpoint_auth_method: private_key_jwt
  scope: idsc:IDS_CONNECTOR_ATTRIBUTES_ALL
  attributes:
  - key: idsc
    value: IDS_CONNECTOR_ATTRIBUTES_ALL
  - key: securityProfile
    value: idsc:BASE_SECURITY_PROFILE
  - key: referringConnector
    value: http://connectorNaturaldisaster.demo
  - key: "@type"
    value: ids:DatPayload
  - key: "@context"
    value: https://w3id.org/idsa/contexts/context.jsonld
  - key: transportCertsSha256
    value: f45cd41d11f62382e63f1242e430ceaaeba42121f65d630e277bc9270a851072
- client_id: 1F:B8:FE:9F:E9:19:AB:BF:D4:CA:8D:88:21:19:84:A5:21:AA:7E:9C:keyid:19:A0:3E:93:17:75:B1:DE:BF:3F:B2:29:F2:FB:02:59:3E:CA:6E:2D
  client_name: connectorCivilservice
  grant_types: client_credentials
  token_endpoint_auth_method: private_key_jwt
  scope: idsc:IDS_CONNECTOR_ATTRIBUTES_ALL
  attributes:
  - key: idsc
    value: IDS_CONNECTOR_ATTRIBUTES_ALL
  - key: securityProfile
    value: idsc:BASE_SECURITY_PROFILE
  - key: referringConnector
    value: http://connectorCivilservice.demo
  - key: "@type"
    value: ids:DatPayload
  - key: "@context"
    value: https://w3id.org/idsa/contexts/context.jsonld
  - key: transportCertsSha256
    value: a8a633694abdb2fccaefb5a970024ee2d21c61ca0d4922bd9fb1d2d67f751b1b
